apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpinfo-deployment
  labels:
    app: phpinfo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: phpinfo
  template:
    metadata:
      labels:
        app: phpinfo
    spec:
      containers:
      - name: phpinfo
        image: mrbbarton/phpinfo:0.0.1
        ports:
        - containerPort: 80
