apiVersion: v1
kind: Service
metadata:
  name: phpinfo-service
spec:
  type: NodePort
  selector:
    app: phpinfo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007